  ## Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/${_IMAGE_PROJECTID}/${_REGISTRY}/${_ENV}-backend-euwest3-01:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/${_IMAGE_PROJECTID}/${_REGISTRY}/${_ENV}-backend-euwest3-01:$COMMIT_SHA']
